import re
p = re.compile("ca{4}t")
m = p.match('caaaat')
print(m)
p = re.compile("ca*t")
m = p.match('cat')
print(m)
p = re.compile("c[a+]t")
m = p.match('caat')
print(m)
p = re.compile("ca{4}t")
m = p.match('caaaat')
print(m)
p = re.compile("ca*t")
m = p.match('cat')
print(m)
p = re.compile("ca{2,}t")
m = p.match('caaaaaaaaaaat')
print(m)
p = re.compile("ca[a+]")
m = p.match('caaa')
print(m)

